### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by caputomarcos** [caputomarcos/gotcha#2]
make pyinstaller

```bash
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.7/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/PyInstaller/__main__.py", line 179, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/PyInstaller/__main__.py", line 60, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 963, in main
    build(specfile, distpath, workpath, clean_build)
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 885, in build
    exec(code, spec_namespace)
  File "/home/user/Projects/gotcha/gotcha.spec", line 7, in <module>
    a = Analysis(
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 410, in __init__
    self.__postinit__()
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 584, in assemble
    self.datas.extend(deps_proc.make_datas_toc())
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/PyInstaller/building/toc_conversion.py", line 111, in make_datas_toc
    toplevel = dist.get_metadata('top_level.txt').strip()
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1431, in get_metadata
    value = self._get(path)
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1635, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Projects/gotcha/.eggs/pyparsing-3.0.9-py3.10.egg/EGG-INFO/top_level.txt'
Traceback (most recent call last):
  File "/home/user/Projects/gotcha/setup.py", line 85, in <module>
    setup(
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 177, in setup
    return run_commands(dist)
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
    dist.run_commands()
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/user/Projects/gotcha/setup.py", line 82, in run
    check_call(command)
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pyinstaller', '--additional-hooks-dir', 'pyinstaller_hooks', '--clean', '--onefile', '--name', 'gotcha', '--hidden-import', 'psutil', '--hidden-import', 'twine', '--hidden-import', 'pyinstaller', '--hidden-import', 'staticx', '--hidden-import', 'future', '--hidden-import', 'packaging', '--hidden-import', 'dataclasses', 'gotcha/__main__.py']' returned non-zero exit status 1.
make: *** [Makefile:42: pyinstaller] Error 1
```

**Comment by caputomarcos** [comment]
pyinstaller --additional-hooks-dir pyinstaller_hooks --clean --onefile --name gotcha --hidden-import psutil --hidden-import twine --hidden-import pyinstaller --hidden-import staticx --hidden-import future --hidden-import packaging --hidden-import dataclasses gotcha/__main__.py

```bash
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.7/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/PyInstaller/__main__.py", line 179, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/PyInstaller/__main__.py", line 60, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 963, in main
    build(specfile, distpath, workpath, clean_build)
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 885, in build
    exec(code, spec_namespace)
  File "/home/user/Projects/gotcha/gotcha.spec", line 7, in <module>
    a = Analysis(
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 410, in __init__
    self.__postinit__()
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 584, in assemble
    self.datas.extend(deps_proc.make_datas_toc())
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/PyInstaller/building/toc_conversion.py", line 111, in make_datas_toc
    toplevel = dist.get_metadata('top_level.txt').strip()
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1431, in get_metadata
    value = self._get(path)
  File "/home/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1635, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Projects/gotcha/.eggs/pyparsing-3.0.9-py3.10.egg/EGG-INFO/top_level.txt'
```

**Comment by caputomarcos** [comment]
**workaround**
```bash
$ touch .eggs/pyparsing-3.0.9-py3.10.egg/EGG-INFO/top_level.txt
$ make installer
```

**Comment by caputomarcos** [comment]
### **Fixed with:**     

**pyparsing==3.0.8**
